# Generated by Django 5.2.6 on 2025-10-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audience_university',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
