# Generated by Django 5.2.6 on 2025-10-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='skills', to='User.education'),
        ),
        migrations.AddField(
            model_name='skill',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='skills', to='User.experience'),
        ),
        migrations.AddField(
            model_name='skill',
            name='license_certificates',
            field=models.ManyToManyField(blank=True, related_name='skills', to='User.licensecertificate'),
        ),
    ]
