# Generated by Django 5.2.6 on 2025-10-21 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_education_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='licensecertificate',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='licensecertificate',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='education',
            name='period_text',
            field=models.CharField(blank=True, help_text="e.g., 2018 – 2022 or '2020 – Present'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='period_text',
            field=models.CharField(blank=True, help_text="e.g., Jan 2021 – Mar 2023 or '2021 – Present'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licensecertificate',
            name='expiry_text',
            field=models.CharField(blank=True, help_text="e.g., Jun 2025 or 'No expiry'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licensecertificate',
            name='issue_text',
            field=models.CharField(blank=True, help_text='e.g., Jun 2022', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='licensecertificate',
            name='issuing_org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AlumniAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_code', models.SlugField(max_length=64, unique=True)),
                ('jitsi_domain', models.CharField(default='meet.jit.si', max_length=128)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='booked', max_length=16)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='User.alumniavailability')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
