# Generated by Django 5.2.6 on 2025-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
