# Generated by Django 5.2.6 on 2025-10-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/defaultpp.png', upload_to='profile_photos/'),
        ),
    ]
