# Generated by Django 5.2.6 on 2025-10-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('connection', 'Connection'), ('message', 'Message'), ('post', 'Post'), ('comment', 'Comment'), ('like', 'Like'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
